[tool.poetry]
name = "quizbottg"
version = "0.1.0"
description = ""
authors = ["Anton Gerasimov <theavg@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
